export const SYMBOL_NODE_TYPE = Symbol('SYMBOL_NODE_TYPE');
export const SYMBOL_NODE_TYPE_NODE_ENTITY = Symbol('SYMBOL_NODE_TYPE_NODE_ENTITY');

export const SYMBOL_COMPONENT_PROPS = Symbol('SYMBOL_COMPONENT_PROPS');
export const SYMBOL_COMPONENT_STATE = Symbol('SYMBOL_COMPONENT_STATE');
export const SYMBOL_COMPONENT_OWNER = Symbol('SYMBOL_COMPONENT_OWNER');
